version: "3"
services:
  move2kubeapi:
    image: quay.io/konveyor/move2kube-api:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./:/workspace"