name: Build

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2
      - run: make ci
      - run: make test-coverage
      - name: upload coverage
        uses: codecov/codecov-action@v1
      - if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#BD3232"
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Build failed in move2kube-api master"
          SLACK_TITLE: Failed
          SLACK_USERNAME: GitHubActions

  image_build:
    needs: [build_and_test]
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull latest image to reuse layers
        run: |
          docker pull quay.io/konveyor/move2kube-api:latest || true
          docker pull quay.io/konveyor/move2kube-api-builder:latest || true
      - name: Build and Push image to quay
        run: |
          echo "${{ secrets.QUAY_BOT_PASSWORD }}" | docker login --username "${{ secrets.QUAY_BOT_USERNAME }}" --password-stdin quay.io
          make cbuild
          make cpush
      - name: success slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Built and pushed quay.io/konveyor/move2kube-api:latest"
          SLACK_TITLE: Success
          SLACK_USERNAME: GitHubActions
      - if: failure()
        name: failure slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#BD3232"
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Failed to build and push image quay.io/konveyor/move2kube-api:latest"
          SLACK_TITLE: Failed
          SLACK_USERNAME: GitHubActions
